# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpu_metrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gpu_metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gpu_metrics.proto\x12\x10gpu_orchestrator\"\x86\x01\n\x11GPUMetricsRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08gpu_uuid\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x12\n\npower_draw\x18\x04 \x01(\x02\x12\x11\n\tvram_used\x18\x05 \x01(\x02\x12\x12\n\nvram_total\x18\x06 \x01(\x02\"5\n\x12GPUMetricsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"5\n\x0e\x41\x63tionResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x13\n\x0btarget_node\x18\x02 \x01(\t2\xca\x01\n\x0fGPUOrchestrator\x12^\n\rStreamMetrics\x12#.gpu_orchestrator.GPUMetricsRequest\x1a$.gpu_orchestrator.GPUMetricsResponse(\x01\x30\x01\x12W\n\x0e\x44ispatchAction\x12#.gpu_orchestrator.GPUMetricsRequest\x1a .gpu_orchestrator.ActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpu_metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GPUMETRICSREQUEST']._serialized_start=40
  _globals['_GPUMETRICSREQUEST']._serialized_end=174
  _globals['_GPUMETRICSRESPONSE']._serialized_start=176
  _globals['_GPUMETRICSRESPONSE']._serialized_end=229
  _globals['_ACTIONRESPONSE']._serialized_start=231
  _globals['_ACTIONRESPONSE']._serialized_end=284
  _globals['_GPUORCHESTRATOR']._serialized_start=287
  _globals['_GPUORCHESTRATOR']._serialized_end=489
# @@protoc_insertion_point(module_scope)
